services:
  objectstorage:
    image: gminio
    networks:
      - cae2s_net
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: "changeme"
      MINIO_ROOT_PASSWORD: "changeme"
    volumes:
      - ./minio_data:/data/

  database:
    image: cae2s-postgres
    networks:
      - cae2s_net
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "changeme"
      POSTGRES_PASSWORD: "changeme"
      POSTGRES_DB: app
    volumes:
      - ./pg_data:/var/lib/postgresql/

  backend:
    image: cae2s
    networks:
      - net
      - cae2s_net
    ports:
      - "8080:8080"
    environment:
      VIRTUAL_HOST: "cea2s.gchalakov.com" 
      LETSENCRYPT_HOST: "cea2s.gchalakov.com" 
      MINIO_ENDPOINT: "objectstorage:9000"
      MINIO_ACCESS_KEY: "changeme"  # Same as MINIO_ROOT_USER
      MINIO_SECRET_KEY: "changeme"  # Same as MINIO_ROOT_PASSWORD
      # DB_USER: $DB_USER 
      # DB_PORT: $DB_PORT 
      # DB_PWD: $DB_PWD 
      # DB_SCHEMA: $DB_SCHEMA 
      # DB_CONTAINER_NAME: $DB_CONTAINER_NAME 
      # OLLAMA_API: $OLLAMA_API 
      # OLLAMA_MODEL: $OLLAMA_MODEL 
      # OLLAMA_CTX: $OLLAMA_CTX 
      # OLLAMA_EMB_API: $OLLAMA_EMB_API 
      # OLLAMA_EMB_MODEL: $OLLAMA_EMB_MODEL 
      # ALLOWED_WS_ORIGIN: $ALLOWED_WS_ORIGIN 

  messagebroker:
    image: rabbitmq:management-alpine
    networks:
      - cae2s_net
    environment:
      RABBITMQ_DEFAULT_USER: "changeme"
      RABBITMQ_DEFAULT_PASS: "changeme"
    ports:
      - "5672:5672"
      - "15672:15672"

networks:
  net:
    external: true
  cae2s_net:
    external: false
