services:
  objectstorage:
    image: gminio
    env_file:
      - ./.env
    networks:
      - cae2s_net
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio_data:/data

  database:
    image: cae2s-postgres
    env_file:
      - ./.env
    networks:
      - cae2s_net
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data

  backend:
    image: cae2s
    env_file:
      - ./.env
    networks:
      - cae2s_net
    ports:
      - "8080:8080"
    depends_on:
      - objectstorage
      - database

  messagebroker:
    image: rabbitmq:management-alpine
    env_file:
      - ./.env
    networks:
      - cae2s_net
    ports:
      - "5672:5672"
      - "15672:15672"

networks:
  cae2s_net:
    driver: bridge
