services:
  objectstorage:
    image: gminio
    networks:
      - network
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: changeme
      MINIO_ROOT_PASSWORD: changeme

  database:
    image: cae2s-postgres
    networks:
      - network
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: changeme
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: app
    volumes:
      - ./pgdata:/var/lib/postgresql/

networks:
  network:
    external: false
