// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.906
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Footer() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<footer class=\"footer\"><div class=\"container\"><div class=\"row\"><div class=\"col-md-6 mb-4 mb-md-0\"><a class=\"navbar-brand mb-3\" href=\"/\"><i class=\"fas fa-microphone-alt\"></i> <span>CAE2<span class=\"logo-highlight\">S</span></span></a><p class=\"text-light\">The premier platform for Cambridge Advanced English speaking practice. Our exercises are designed to help you master all parts of the CAE C1 speaking exam.</p><div class=\"mt-3\"><a href=\"#\" class=\"btn btn-outline-light me-2\"><i class=\"fab fa-facebook-f\"></i></a> <a href=\"#\" class=\"btn btn-outline-light me-2\"><i class=\"fab fa-twitter\"></i></a> <a href=\"#\" class=\"btn btn-outline-light me-2\"><i class=\"fab fa-instagram\"></i></a> <a href=\"#\" class=\"btn btn-outline-light\"><i class=\"fab fa-linkedin-in\"></i></a></div></div><div class=\"col-md-3 mb-4 mb-md-0\"><h5 class=\"text-light mb-3\">Quick Links</h5><ul class=\"list-unstyled\"><li class=\"mb-2\"><a href=\"/\" class=\"text-light\">Home</a></li><li class=\"mb-2\"><a href=\"#\" class=\"text-light\">Practice Exercises</a></li><li class=\"mb-2\"><a href=\"#\" class=\"text-light\">Exam Tips</a></li><li class=\"mb-2\"><a href=\"#\" class=\"text-light\">Pricing</a></li><li><a href=\"#\" class=\"text-light\">Contact Us</a></li></ul></div><div class=\"col-md-3\"><h5 class=\"text-light mb-3\">Legal</h5><ul class=\"list-unstyled\"><li class=\"mb-2\"><a href=\"#\" class=\"text-light\">Terms of Service</a></li><li class=\"mb-2\"><a href=\"#\" class=\"text-light\">Privacy Policy</a></li><li><a href=\"#\" class=\"text-light\">Cookie Policy</a></li></ul></div></div><div class=\"text-center mt-5 pt-3 border-top border-secondary\"><p class=\"company-info\">&copy; 2025 CAE2S Speaking Practice Platform<br>Developed by <span style=\"color: var(--accent-color);\">PulpuDEV LTD</span></p></div></div></footer>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
